version: "3.8"

services:

  accounts:
    image: mipatrik/accounts:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network

  loans:
    image: mipatrik/loans:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network

  cards:
    image: mipatrik/cards:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "9010:9010"
    networks:
      - eazybank-network

networks:
  eazybank-network: