version: "3.8"

services:

  configserver:
    image: mipatrik/configserver:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - pmbank-network

  accounts:
    image: mipatrik/accounts:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:8080"
    networks:
      - pmbank-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: mipatrik/loans:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8090:8090"
    networks:
      - pmbank-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: mipatrik/cards:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9010:9010"
    networks:
      - pmbank-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  pmbank-network: