version: "3.8"

services:
  configserver:
    image: mipatrik/configserver:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - pmbank-network

  eurekaserver:
    image: mipatrik/eurekaserver:latest
    ports:
      - "8070:8070"
    networks:
      - pmbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: mipatrik/accounts:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:8080"
    networks:
      - pmbank-network
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

#   Second instance of accounst microservice
#  accounts1:
#    image: mipatrik/accounts:latest
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 3
#        window: 120s
#    ports:
#      - "8081:8080"
#    networks:
#      - pmbank-network
#    depends_on:
#      - configserver
#      - eurekaserver
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: mipatrik/loans:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    ports:
      - "8090:8090"
    networks:
      - pmbank-network
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: mipatrik/cards:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    ports:
      - "9010:9010"
    networks:
      - pmbank-network
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  gatewayserver:
    image: mipatrik/gatewayserver:latest
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    ports:
      - "8072:8072"
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    networks:
      - pmbank-network
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  pmbank-network: